/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// TODO rename this file after amplify pull project_id.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
};


export default awsmobile;
